module.exports = {
  "h300" : [2, [CARRY, CARRY, CARRY, MOVE, WORK]], 
  "b300" : [2, [CARRY, MOVE, WORK, WORK]],
  "u300" : [0, [CARRY, CARRY, MOVE, WORK]],
  "d300" : [3, [CARRY, MOVE, WORK, WORK]],
  "r300" : [1, [CARRY, MOVE, WORK]],
  "c300" : [0, [CARRY, MOVE]],
  "a300" : [1, [TOUGH,TOUGH,TOUGH,TOUGH,RANGED_ATTACK, MOVE]],
  "he300" : [1, [HEAL, MOVE]],
  
  "h400" : [2, [CARRY, CARRY, CARRY, MOVE, MOVE, WORK]],
  "b400" : [3, [CARRY, CARRY, CARRY, MOVE, MOVE, WORK]],
  "u400" : [0, [CARRY, MOVE, WORK, WORK, WORK]],
  "d400" : [2, [CARRY, MOVE, WORK, WORK, WORK]],
  "c400" : [2, [CARRY, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE]],

  "h500" : [2, [CARRY, CARRY, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE, WORK]],
  "b500" : [3, [CARRY, CARRY, CARRY, MOVE, WORK, WORK, WORK]],
  "u500" : [2, [CARRY, CARRY, MOVE, MOVE, WORK, WORK, WORK]],
  "d500" : [2, [CARRY, MOVE, WORK, WORK, WORK, WORK]],
  "r500" : [1, [MOVE,MOVE,WORK,WORK,CARRY,CARRY,CARRY,CARRY]],
  "c500" : [2, [MOVE,MOVE,MOVE,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY]],
  "a500" : [1, [TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,MOVE,ATTACK,RANGED_ATTACK]],
  
  "h600" : [2, [MOVE,MOVE,MOVE,MOVE,WORK,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY]],
  "b600" : [2, [CARRY, CARRY, CARRY, CARRY, MOVE, MOVE, WORK, WORK, WORK]],
  "u600" : [2, [CARRY, CARRY, CARRY, MOVE, MOVE, MOVE, WORK, WORK, WORK]],
  "d600" : [2, [CARRY, MOVE, WORK, WORK, WORK, WORK, WORK]],
  "c600" : [3, [MOVE,MOVE,MOVE,MOVE,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY]],
  
  "r700" :[1, [MOVE,MOVE,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY]],
  
  "d800" : [1, [CARRY, MOVE, WORK, WORK, WORK, WORK, WORK, WORK, WORK]],
  "c800" : [3, [MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY]],
  
  "d1000" : [1, [CARRY, MOVE, MOVE, MOVE, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK]],
  "c1000" : [1, [MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY]],
  "u1000" : [2, [CARRY, MOVE, MOVE, MOVE, WORK, WORK, WORK, WORK, WORK, WORK, WORK, WORK]],
  
  "cl300" : [1, [CLAIM, CLAIM, MOVE, MOVE]],
};